# Generated by Django 5.1.11 on 2025-08-26 16:42

import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=3, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='knowledgedb_name_4c5555_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('short__regex', '^[A-Z]{2}$')), name='ck_nation_short_upper')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('birthdate', models.DateField()),
                ('playing_since', models.DateField()),
                ('eura_pro', models.BooleanField()),
                ('hometeam', models.CharField(max_length=120)),
                ('speciality', models.CharField(max_length=200)),
                ('achievements', models.TextField()),
                ('normal_teammate', models.ManyToManyField(to='knowledgedb.player')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='squads', to='knowledgedb.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('division', models.CharField(choices=[('coed', 'Coed'), ('open', 'Open'), ('women', 'Women')], max_length=5)),
                ('playerA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_playerA', to='knowledgedb.player')),
                ('playerB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_playerB', to='knowledgedb.player')),
            ],
        ),
        migrations.CreateModel(
            name='SquadTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_teams', to='knowledgedb.squad')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='squad_teams', to='knowledgedb.team')),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='squads', through='knowledgedb.SquadTeam', to='knowledgedb.team'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('division', models.CharField(choices=[('coed', 'Coed'), ('open', 'Open'), ('women', 'Women')], max_length=5)),
            ],
            options={
                'indexes': [models.Index(fields=['start_date'], name='knowledgedb_start_d_73fcd5_idx'), models.Index(fields=['division', 'start_date'], name='knowledgedb_divisio_3d413d_idx')],
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='knowledgedb.tournament'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['lastname', 'firstname'], name='knowledgedb_lastnam_fc48a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('firstname', 'lastname', 'birthdate'), name='uq_player_name_dob'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(django.db.models.functions.comparison.Least('playerA', 'playerB'), django.db.models.functions.comparison.Greatest('playerA', 'playerB'), name='idx_team_pair_unordered'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('playerA', models.F('playerB')), _negated=True), name='ck_team_two_distinct_players'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('playerA', 'playerB'), django.db.models.functions.comparison.Greatest('playerA', 'playerB'), name='uq_team_player_pair_unordered'),
        ),
        migrations.AddIndex(
            model_name='squadteam',
            index=models.Index(fields=['team'], name='knowledgedb_team_id_f52d77_idx'),
        ),
        migrations.AddIndex(
            model_name='squadteam',
            index=models.Index(fields=['squad', 'seed'], name='knowledgedb_squad_i_7da9ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='squadteam',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('squad', 'seed'), name='uq_squad_seed_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='squadteam',
            unique_together={('squad', 'team')},
        ),
        migrations.AddIndex(
            model_name='squad',
            index=models.Index(fields=['tournament', 'nation'], name='knowledgedb_tournam_73cc92_idx'),
        ),
        migrations.AddConstraint(
            model_name='squad',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tournament', 'nation'), name='uq_squad_unique_nation_per_tournament'),
        ),
    ]
