# Generated by Django 5.1.11 on 2025-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nation',
            name='ck_nation_short_upper',
        ),
        migrations.AddConstraint(
            model_name='nation',
            constraint=models.CheckConstraint(condition=models.Q(('short__regex', '^[A-Z]{3}$')), name='ck_nation_short_upper'),
        ),
    ]
