# Generated by Django 5.1.11 on 2025-08-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgedb', '0002_remove_nation_ck_nation_short_upper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AlterField(
            model_name='player',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hometeam',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='player',
            name='normal_teammate',
            field=models.ManyToManyField(blank=True, to='knowledgedb.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_since',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='speciality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
