# Generated by Django 5.1.11 on 2025-08-26 17:13

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgedb', '0003_remove_team_name_alter_player_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='uq_player_name_dob',
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('firstname', 'lastname'), name='uq_player_name_dob'),
        ),
    ]
