# Generated by Django 5.1.11 on 2025-08-26 17:16

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgedb', '0004_remove_player_uq_player_name_dob_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='uq_player_name_dob',
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('firstname', 'lastname', 'birthdate'), name='uq_player_name_dob'),
        ),
    ]
