# Generated by Django 5.1.11 on 2025-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgedb', '0005_remove_player_uq_player_name_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='normal_teammate',
            field=models.ManyToManyField(blank=True, null=True, to='knowledgedb.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
