# Generated by Django 5.1.11 on 2025-08-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgedb', '0006_alter_player_normal_teammate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
