# Generated by Django 5.1.11 on 2025-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgedb', '0007_squad_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='add_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nation',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
